version: '3.3'

services:
  covee:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    volumes:
      - .:/covee-service
    command: python3 covee_main.py
     
    ports:
      - 7071:8000